Throw error rather than wait for TTY input.

diff --git a/bin/grapht b/bin/grapht
--- a/bin/grapht
+++ b/bin/grapht
@@ -8,7 +8,13 @@ if [ $? -ne 0 ]; then
 fi
 
 if [ "$#" -ge 1 ]; then
-  phantomjs $script $@ < /dev/stdin
+  if [ ! -t 0 ]; then
+    phantomjs $script $@ < /dev/stdin
+  else
+    echo "ERROR:"
+    echo "-- grapht was called without STDIN data."
+    exit 1
+  fi
 else
   echo "ERROR:"
   echo "-- grapht was called with unknown arguments:"
